### ISSUE TITLE
Failed to install from test PyPI, problem of installing IPython

### ISSUE THREAD

**Issue by marvinmin** [UBC-MDS/edapython#80]
When installing from test PyPI, there is an error about IPython.
```
ERROR: Could not find a version that satisfies the requirement IPython<8.0.0,>=7.13.0 (from eda-analysis) (from versions: none)
ERROR: No matching distribution found for IPython<8.0.0,>=7.13.0 (from eda-analysis)
```

**Comment by marvinmin** [comment]
It seems the only function using IPython is the `generate_report()` function. We used `.display()` to show the `Altair` plot. @sgauravm, Is there any way to avoid using the function?

I tried to remove the `.display()` function in the prepare_publish branch. But I think the wrapper function will have a problem of showing the plots at the same time.

**Comment by marvinmin** [comment]
Reopen. 
Using a fixed IPython version still has the similar error:
```
ERROR: Could not find a version that satisfies the requirement IPython==7.13.0 (from eda-analysis) (from versions: none)
ERROR: No matching distribution found for IPython==7.13.0 (from eda-analysis)
```

**Comment by v5y8** [comment]
do you have to specify a version of IPython?
maybe the version requirement's too stringent.

**Comment by sweber15** [comment]
I was trying to read why it is happening:

- https://pypi.org/help/#tls-deprecation
- https://github.com/pypa/packaging-problems/issues/177

I'd say try the first one to see if you can get more information. If not there might be a version issue maybe try something like ^7.0.0.

**Comment by sgauravm** [comment]
Is it only IPython? Let me try some other way to display the plot if possible.So we won't be facing this issue

**Comment by marvinmin** [comment]
I tried to remove the version limit of IPython in pull request #83. If it doesn't, I'll push the function without using IPython.
